---
# Handlers for Logging Role

- name: restart docker
  service:
    name: docker
    state: restarted
  become: true

- name: restart systemd-journald
  service:
    name: systemd-journald
    state: restarted
  become: true
