---
# Dependencies Installation Role
# Install required system packages and Python modules

- name: Update package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true
  register: update_cache_result
  ignore_errors: true

- name: Update package cache with --fix-missing
  command: apt-get update --fix-missing
  become: true
  register: fix_missing_result
  ignore_errors: true

- name: Install Python package manager
  command: apt-get install -y python3-pip
  become: true
  register: python_packages
  ignore_errors: true

- name: Install version control and network tools
  apt:
    name:
      - git
      - curl
      - wget
    state: present
  become: true
  register: network_tools
  ignore_errors: true

- name: Install build tools
  apt:
    name:
      - build-essential
    state: present
  become: true
  register: build_tools
  ignore_errors: true

- name: Install package management tools
  apt:
    name:
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
    state: present
  become: true
  register: package_tools
  ignore_errors: true

- name: Install Python venv module (ensure ensurepip is available)
  apt:
    name: python3-venv
    state: present
  become: true

- name: Create Python virtual environment
  command: python3 -m venv /opt/gonka-venv
  become: true
  args:
    creates: /opt/gonka-venv

- name: Install Python packages in virtual environment
  command: /opt/gonka-venv/bin/pip install huggingface_hub
  become: true
  async: 300  # 5 minutes timeout
  poll: 30    # Check every 30 seconds

- name: Create pip wrapper script for system-wide access
  copy:
    content: |
      #!/bin/bash
      exec /opt/gonka-venv/bin/pip "$@"
    dest: /usr/local/bin/gonka-pip
    mode: '0755'
  become: true

- name: Create PATH helper script
  copy:
    content: |
      #!/bin/bash
      export PATH="/opt/gonka-venv/bin:$PATH"
      exec "$@"
    dest: /usr/local/bin/with-gonka-venv
    mode: '0755'
  become: true

- name: Create Hugging Face cache directory
  file:
    path: "{{ hf_home }}"
    state: directory
    mode: '0755'
    owner: ubuntu
    group: ubuntu
  become: true

- name: Display installation completion
  debug:
    msg: |
      ✅ Dependencies installed on {{ inventory_hostname }}
      📦 Python packages: huggingface_hub, transformers, torch (in virtual environment)
      📁 HF_HOME: {{ hf_home }}
      🔧 Environment: Configured
