---
# Gonka Two-Cluster Deployment Playbook
# Deploys two independent clusters with model distribution

- name: Phase 0 - Account Key Setup (Network Nodes)
  hosts: cluster1_network_node:cluster2_network_node
  gather_facts: false
  vars_files:
    - ../vars/main.yml
  roles:
    - key-setup
  tags: ['phase0', 'key-setup', 'account-keys']

- name: Phase 1 - Environment Setup & Pre-Validation
  hosts: gonka_clusters
  gather_facts: true
  vars_files:
    - ../vars/main.yml
  roles:
    - pre-validation
  tags: ['phase1', 'pre-validation', 'environment']

- name: Phase 1.4 - Dependency Installation
  hosts: gonka_clusters
  vars_files:
    - ../vars/main.yml
  roles:
    - dependencies
  tags: ['phase1', 'dependencies', 'packages']

- name: Phase 2.1.1 - Repository
  hosts: gonka_clusters
  vars_files:
    - ../vars/main.yml
  roles:
    - git
  tags: ['phase2', 'git']

- name: Phase 2.1.2 - Model Preparation
  hosts: gonka_clusters
  vars_files:
    - ../vars/main.yml
  roles:
    - huggingface
  tags: ['phase2', 'huggingface']

- name: Phase 2.1.3 - Docker Pull
  hosts: gonka_clusters
  vars_files:
    - ../vars/main.yml
  roles:
    - docker
  tags: ['phase2', 'docker']

- name: Phase 2.2 - Firewall Configuration
  hosts: gonka_clusters
  vars_files:
    - ../vars/main.yml
  roles:
    - firewall
  tags: ['phase2', 'firewall']

- name: Phase 2.1 - Post-Repository Validation
  hosts: gonka_clusters
  vars_files:
    - ../vars/main.yml
  roles:
    - repo-validation
  tags: ['phase2', 'repo-validation']

- name: Phase 3 - Key Management & Configuration
  hosts: gonka_clusters
  vars_files:
    - ../vars/main.yml
  roles:
    - config
  tags: ['phase3', 'config', 'key-management']

- name: Phase 3.2 - Initial Services Launch (Network Nodes Only)
  hosts: cluster1_network_node:cluster2_network_node
  vars_files:
    - ../vars/main.yml
  roles:
    - network-init
  tags: ['phase3', 'network-init', 'blockchain-init']

- name: Phase 3.3 - Cryptographic Key Setup (Network Nodes Only)
  hosts: cluster1_network_node:cluster2_network_node
  vars_files:
    - ../vars/main.yml
  roles:
    - keygen
  tags: ['phase3', 'keygen', 'ml-key']

- name: Phase 3.4 - Host Registration (Network Nodes Only)
  hosts: cluster1_network_node:cluster2_network_node
  vars_files:
    - ../vars/main.yml
  roles:
    - registration
  tags: ['phase3', 'registration', 'host-registration']

- name: Phase 3.5 - Permission Granting (Network Nodes)
  hosts: cluster1_network_node:cluster2_network_node
  gather_facts: false
  vars_files:
    - ../vars/main.yml
  roles:
    - permissions
  tags: ['phase3', 'permissions', 'ml-permissions']

- name: Phase 4 - Full Node Activation (Network Nodes Only)
  hosts: cluster1_network_node:cluster2_network_node
  vars_files:
    - ../vars/main.yml
  roles:
    - network-full
  tags: ['phase4', 'network-full', 'full-activation']

- name: Phase 5 - ML Nodes Deployment
  hosts: cluster1_ml_nodes:cluster2_ml_nodes
  vars_files:
    - ../vars/main.yml
  roles:
    - ml-deploy
  tags: ['phase5', 'ml-deploy', 'inference-nodes']

- name: Phase 5.2 - ML Node Registration
  hosts: cluster1_network_node:cluster2_network_node
  vars_files:
    - ../vars/main.yml
  roles:
    - ml-register
  tags: ['phase5', 'ml-register', 'node-registration']

- name: Phase 6 - Verification & Health Checks
  hosts: gonka_clusters
  vars_files:
    - ../vars/main.yml
  roles:
    - validation
    - cluster-check
    - performance
  tags: ['phase6', 'validation', 'cluster-check', 'performance', 'health-check']

# - name: Phase 7 - Monitoring & Maintenance Setup
#   hosts: gonka_clusters
#   vars_files:
#     - ../vars/main.yml
#   roles:
#     - logging
#     - monitoring
#     - backup
#   tags: ['phase7', 'logging', 'monitoring', 'backup', 'maintenance']
